# Generated by Django 3.1.5 on 2022-09-10 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'auth_user'},
        ),
    ]
