# Generated by Django 3.1.5 on 2022-08-25 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20220824_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='reply',
            field=models.ManyToManyField(related_name='replied', to='articles.Comment'),
        ),
    ]
