# Generated by Django 3.1.5 on 2022-09-18 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OutboundStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(max_length=250)),
                ('package_code', models.CharField(max_length=250)),
                ('transfer_company', models.CharField(choices=[('EMS', 'EMS'), ('EMS_PREMIUM', 'EMS_PREMIUM'), ('EMS_TAIWAN', 'EMS_TAIWAN'), ('PANTOS', 'PANTOS'), ('CAINAO', 'CAINAO'), ('YTO', 'YTO'), ('YUNDA', 'YUNDA')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='OutboundInvoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.CharField(max_length=250)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='printers.outboundstock')),
            ],
        ),
        migrations.CreateModel(
            name='OutboundEncryptedInvoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encrypted_data', models.CharField(max_length=250)),
                ('sign', models.CharField(max_length=250)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encrypted_invoice', to='printers.outboundstock')),
            ],
        ),
    ]
