# Generated by Django 3.1.5 on 2022-09-21 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=250)),
                ('price', models.DecimalField(decimal_places=0, max_digits=5)),
                ('discount_price', models.DecimalField(decimal_places=0, max_digits=5)),
            ],
        ),
    ]
