# Generated by Django 3.1.5 on 2022-10-06 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(choices=[('COSMETIC', 'COSMETIC'), ('FOOD', 'FOOD'), ('BOOK', 'BOOK')], max_length=250)),
            ],
        ),
    ]
