# Generated by Django 3.1.5 on 2022-10-06 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(choices=[('카테고리 종류', 'Help'), ('COSMETIC', 'Cosmetic'), ('FOOD', 'Food'), ('BOOK', 'Book')], max_length=250),
        ),
    ]
