# Generated by Django 3.1.5 on 2022-10-06 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0004_auto_20221006_1702'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='category',
            constraint=models.CheckConstraint(check=models.Q(category_name__in=['COSMETIC', 'FOOD', 'BOOK']), name='stocks_category_category_name_valid'),
        ),
    ]
