# Generated by Django 3.1.5 on 2022-10-06 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0005_auto_20221006_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='something_price',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.CheckConstraint(check=models.Q(something_price__gte=0), name='stocks_category_something_price_valid'),
        ),
    ]
