# Generated by Django 3.1.5 on 2022-10-06 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0006_auto_20221006_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='something_price',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
    ]
