openapi: 3.0.0
info:
  title: OpenAPI Demo
  version: 0.0.1
externalDocs:
  description: OpenAPI Demo
  url: http://localhost/graphql
servers:
- url: http://localhost:{port}/graphql
  variables:
    port:
      enum:
      - '8000'
      default: '8000'
tags:
- name: Query
  description: 쿼리
- name: Mutation
  description: 뮤테이션
paths:
  /DeleteArticleMutation:
    summary: DeleteArticleMutation
    post:
      tags:
      - Mutation
      summary: DeleteArticleMutation
      responses:
        200:
          description: 200 success
  /CreateCommentMutation:
    summary: CreateCommentMutation
    post:
      tags:
      - Mutation
      summary: CreateCommentMutation
      responses:
        200:
          description: 200 success
  /GetOutboundInvoiceMutation:
    summary: GetOutboundInvoiceMutation
    post:
      tags:
      - Mutation
      summary: 출고 주문 송장 정보 가져오기
      responses:
        200:
          description: 200 success
  /CreateArticleMutation:
    summary: CreateArticleMutation
    post:
      tags:
      - Mutation
      summary: CreateArticleMutation
      responses:
        200:
          description: 200 success
  /Query:
    summary: Query
    post:
      tags:
      - Query
      summary: Query
      responses:
        200:
          description: 200 success
  /IsDuplicateEmailMutation:
    summary: IsDuplicateEmailMutation
    post:
      tags:
      - Mutation
      summary: 이메일 중복 여부
      responses:
        200:
          description: 200 success
  /UserQuery:
    summary: UserQuery
    post:
      tags:
      - Query
      summary: UserQuery
      responses:
        200:
          description: 200 success
  /Mutation:
    summary: Mutation
    post:
      tags:
      - Mutation
      summary: Mutation
      responses:
        200:
          description: 200 success
  /UpdateArticleMutation:
    summary: UpdateArticleMutation
    post:
      tags:
      - Mutation
      summary: 게시글 수정
      responses:
        200:
          description: 200 success
  /ArticleQuery:
    summary: ArticleQuery
    post:
      tags:
      - Query
      summary: ArticleQuery
      responses:
        200:
          description: 200 success


