openapi: 3.0.0
info:
  title: OpenAPI Demo
  version: 0.0.1
externalDocs:
  description: OpenAPI Demo
  url: http://localhost/graphql
servers:
- url: http://localhost:{port}/graphql
  variables:
    port:
      enum:
      - '8000'
      default: '8000'
tags:
- name: Query
  description: 쿼리
- name: Mutation
  description: 뮤테이션
paths:
  /GetOutboundInvoiceMutation:
    summary: GetOutboundInvoiceMutation
    post:
      tags:
      - Mutation
      summary: 출고 주문 송장 정보 가져오기
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                product_code:
                  type: String
      responses:
        200:
          description: whether success or fail, it always 200
  /Query:
    summary: Query
    post:
      tags:
      - Query
      summary: Query
      requestBody: {}
      responses:
        200:
          description: whether success or fail, it always 200
  /CreateCommentMutation:
    summary: CreateCommentMutation
    post:
      tags:
      - Mutation
      summary: CreateCommentMutation
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                content:
                  type: string
                user_id:
                  type: ID
                article_id:
                  type: ID
      responses:
        200:
          description: whether success or fail, it always 200
  /Mutation:
    summary: Mutation
    post:
      tags:
      - Mutation
      summary: Mutation
      requestBody: {}
      responses:
        200:
          description: whether success or fail, it always 200
  /DeleteArticleMutation:
    summary: DeleteArticleMutation
    post:
      tags:
      - Mutation
      summary: DeleteArticleMutation
      requestBody: {}
      responses:
        200:
          description: whether success or fail, it always 200
  /UpdateArticleMutation:
    summary: UpdateArticleMutation
    post:
      tags:
      - Mutation
      summary: 게시글 수정
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: String
                content:
                  type: String
      responses:
        200:
          description: whether success or fail, it always 200
  /ArticleQuery:
    summary: ArticleQuery
    post:
      tags:
      - Query
      summary: ArticleQuery
      requestBody: {}
      responses:
        200:
          description: whether success or fail, it always 200
  /CreateArticleMutation:
    summary: CreateArticleMutation
    post:
      tags:
      - Mutation
      summary: CreateArticleMutation
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: String
                content:
                  type: String
                creator_id:
                  type: ID
      responses:
        200:
          description: whether success or fail, it always 200
        CustomException:
          description: 커스텀 입셉션
        SomethingException:
          description: 뭔가 뭔가 입셉션
  /UserQuery:
    summary: UserQuery
    post:
      tags:
      - Query
      summary: UserQuery
      requestBody: {}
      responses:
        200:
          description: whether success or fail, it always 200
  /IsDuplicateEmailMutation:
    summary: IsDuplicateEmailMutation
    post:
      tags:
      - Mutation
      summary: 이메일 중복 여부
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: String
      responses:
        200:
          description: whether success or fail, it always 200


